import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Logo } from "@/components/Logo";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SURAA",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider publishableKey="pk_test_ZXF1aXBwZWQtZ29hdC03Mi5jbGVyay5hY2NvdW50cy5kZXYk">
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="flex justify-between items-center px-6 py-4 gap-4 h-16 ">
            <Logo />
            <div className="flex gap-4 z-10">
              <SignedOut>
                <SignInButton>
                  <button className=" font-semibold hover:text-gray-400">
                    Sign In
                  </button>
                </SignInButton>

                <SignUpButton>
                  <button className=" font-semibold hover:text-gray-400">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>
              <SignedIn>
                <UserButton />
              </SignedIn>
            </div>
          </header>

          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
